version: 0.2

env:
  variables:
    REGION: "sa-east-1"
    ACCOUNT_ID: "248189947068"
    CLUSTER_NAME: "sas-6881323-eks"
    REPOSITORY: "dataiesb-site"
    DEPLOYMENT_NAME: "dataiesb-app"
    CONTAINER_NAME: "dataiesb-container"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - echo Verifying kubectl...
      - kubectl version --client
      - pip install --upgrade awscli

  pre_build:
    commands:
      - export ECR_REGION=us-east-1
      - export BUILD_REGION=sa-east-1
      - export ACCOUNT_ID=248189947068
      - export REPOSITORY=dataiesb-site
      - echo Logging in to Amazon ECR in $ECR_REGION...
      - aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com
      - export REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$ECR_REGION.amazonaws.com/$REPOSITORY
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - aws eks update-kubeconfig --name $CLUSTER_NAME --region $BUILD_REGION

  build:
    commands:
      - echo Building the Docker image...
      - |
        docker build \
          --build-arg REPOSITORY_URI=$REPOSITORY_URI \
          --build-arg SCHEMA=$SCHEMA \
          --build-arg DB_NAME=$DB_NAME \
          --build-arg JWT_SECRET_KEY=$JWT_SECRET_KEY \
          --build-arg DATABASE_URL=$DATABASE_URL \
          -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest


  post_build:
    commands:
      - echo Pushing Docker images to ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Updating deployment in EKS...
      - kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=$REPOSITORY_URI:$IMAGE_TAG -n default
      - kubectl rollout status deployment/$DEPLOYMENT_NAME -n default

