version: 0.2

phases:
  pre_build:
    commands:
      - echo "🔑 Logging in to Amazon ECR..."
      - aws --version
      - $(aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com)
      - echo "🔍 Setting environment variables from config..."
      - export ECR_REPO=$(python3 -c "from config_files import config; print(config.ECR_REPO)")
      - export AWS_ACCOUNT_ID=$(python3 -c "from config_files import config; print(config.AWS_ACCOUNT_ID)")
      - export REPOSITORY_URI=$(python3 -c "from config_files import config; print(config.REPOSITORY_URI)")
      - export DOCKER_IMAGE=$(python3 -c "from config_files import config; print(config.DOCKER_IMAGE)")
      - export CONTAINER_NAME=$(python3 -c "from config_files import config; print(config.CONTAINER_NAME)")
      - echo "Environment variables set."

  build:
    commands:
      - echo "🛠️ Building Docker image..."
      - docker build --no-cache -t $DOCKER_IMAGE -f docker/Dockerfile .
      - docker tag $DOCKER_IMAGE:latest $REPOSITORY_URI:latest

  post_build:
    commands:
      - echo "🚀 Pushing Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - echo "✅ Build and push completed."

artifacts:
  files:
    - '**/*'

