version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 248189947068.dkr.ecr.us-east-1.amazonaws.com
      
      # Set variables
      - REPOSITORY_URI=248189947068.dkr.ecr.us-east-1.amazonaws.com/dataiesb-site
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

  build:
    commands:
      - echo Building the Docker image...
      - docker build --build-arg REPOSITORY_URI=$REPOSITORY_URI --build-arg SCHEMA=$SCHEMA --build-arg DB_NAME=$DB_NAME --build-arg JWT_SECRET_KEY=$JWT_SECRET_KEY --build-arg DATABASE_URL=$DATABASE_URL -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $REPOSITORY_URI:latest


  post_build:
    commands:
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest

artifacts:
  files: '**/*'

